bump to v4

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -77,6 +77,12 @@ jobs:
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
       - name: Static HTML export with Next.js
         run: ${{ steps.detect-package-manager.outputs.runner }} next export
+      - name: Verify export directory
+        run: |
+          if [ ! -d "./out" ]; then
+            echo "Error: Export directory './out' does not exist."
+            exit 1
+          fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v1
         with:
